import { BaseDto } from 'ws-request-hook';
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.3.0.0 (NJsonSchema v11.2.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming




export interface MemberLeftNotification extends BaseDto {
    clientId?: string;
    topic?: string;
}

export interface ServerSendsErrorMessage extends BaseDto {
    message?: string;
}

/** Available eventType and string constants */
export enum StringConstants {
    MemberLeftNotification = "MemberLeftNotification",
    ServerSendsErrorMessage = "ServerSendsErrorMessage",
}

